/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-bright": "#31394d",
        "primary": "#c0c1ff",
        "inverse-on-surface": "#283044",
        "on-secondary-fixed": "#001e2f",
        "outline": "#908fa0",
        "error-container": "#93000a",
        "outline-variant": "#464554",
        "surface": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-secondary-container": "#00344e",
        "on-tertiary": "#003824",
        "on-tertiary-fixed": "#002113",
        "surface-container-highest": "#2d3449",
        "primary-fixed": "#e1e0ff",
        "inverse-primary": "#494bd6",
        "surface-dim": "#0b1326",
        "on-tertiary-container": "#000703",
        "background": "#0b1326",
        "error": "#ffb4ab",
        "tertiary-fixed": "#6ffbbe",
        "tertiary": "#4edea3",
        "surface-container-lowest": "#060e20",
        "surface-variant": "#2d3449",
        "on-surface-variant": "#c7c4d7",
        "tertiary-container": "#00885d",
        "on-secondary": "#00344d",
        "surface-container": "#171f33",
        "secondary": "#89ceff",
        "on-primary-container": "#0d0096",
        "on-surface": "#dae2fd",
        "on-error": "#690005",
        "secondary-container": "#00a2e6",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#c9e6ff",
        "on-primary": "#1000a9",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#222a3d",
        "on-background": "#dae2fd",
        "on-secondary-fixed-variant": "#004c6e",
        "on-error-container": "#ffdad6",
        "primary-container": "#8083ff",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#07006c",
        "secondary-fixed-dim": "#89ceff",
        "surface-tint": "#c0c1ff"
      },
      "spacing": {
        "gutter-dense": "0.5rem",
        "space-lg": "1rem",
        "space-2xs": "0.125rem",
        "margin-compact": "0.75rem",
        "space-xl": "1.5rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-2xl": "2rem",
        "margin": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "mono-data": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"]
      },
    },
  },
  plugins: [],
}
